import type { CategoryID } from './categories.data'
import type { PropertyID } from './properties.data'

export const CATEGORY_NON_PROPERTIES: Partial<Record<CategoryID, [PropertyID, string][]>> = {
	'0': [['inhabited', '']],
	'2': [['connected', '']],
	'Set': [
		['strict terminal object', ''],
		['skeletal', 'trivial'],
	],
	'Ab': [
		['split abelian', ''],
		['skeletal', 'trivial'],
	],
	'Top': [
		['cartesian closed', ''],
		['locally presentable', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['cogenerator', ''],
		['exact filtered colimits', ''],
		['skeletal', 'trivial'],
	],
	'Grp': [
		['subobject classifier', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'Vect': [
		['trivial', ''],
		['skeletal', 'trivial'],
	],
	'Ring': [
		['strict initial object', ''],
		['balanced', ''],
		['cogenerator', ''],
		['disjoint finite coproducts', ''],
		['skeletal', 'trivial'],
	],
	'CRing': [
		['strict initial object', ''],
		['balanced', ''],
		['cogenerator', ''],
		['disjoint finite coproducts', ''],
		['skeletal', 'trivial'],
	],
	'Rng': [
		['preadditive', ''],
		['balanced', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'FinSet': [
		['small', ''],
		['strict terminal object', ''],
		['sequential limits', ''],
		['sequential colimits', ''],
		['skeletal', 'trivial'],
	],
	'FinAb': [
		['small', ''],
		['generator', ''],
		['split abelian', ''],
		['sequential limits', ''],
		['skeletal', 'trivial'],
	],
	'Abfg': [
		['small', ''],
		['cogenerator', ''],
		['split abelian', ''],
		['countable products', ''],
		['countable coproducts', ''],
		['skeletal', 'trivial'],
	],
	'Set*': [
		['preadditive', ''],
		['skeletal', 'trivial'],
	],
	'sSet': [
		['strict terminal object', ''],
		['skeletal', 'trivial'],
	],
	'Mon': [
		['preadditive', ''],
		['balanced', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'Pos': [
		['strict terminal object', ''],
		['finitary algebraic', ''],
		['balanced', ''],
		['skeletal', 'trivial'],
	],
	'I': [['subobject classifier', '']],
	'M-Set': [
		['strict terminal object', ''],
		['skeletal', 'trivial'],
	],
	'R-Mod': [
		['split abelian', ''],
		['skeletal', 'trivial'],
	],
	'Met': [
		['sequential limits', ''],
		['finite coproducts', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['cartesian closed', ''],
		['essentially small', ''],
		['exact filtered colimits', '2.7 in https://arxiv.org/abs/2006.01399'],
		['skeletal', 'trivial'],
	],
	'Met_oo': [
		['strict terminal object', ''],
		['balanced', ''],
		['cartesian closed', ''],
		['exact filtered colimits', '2.7 in https://arxiv.org/abs/2006.01399'],
		['skeletal', 'trivial'],
	],
	'Met_c': [
		['products', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['cartesian closed', ''],
		['skeletal', 'trivial'],
	],
	'Ban': [
		['preadditive', ''],
		['balanced', ''],
		['exact filtered colimits', ''],
		['skeletal', 'trivial'],
	],
	'Man': [
		['essentially small', ''],
		['countable products', ''],
		['coproducts', ''],
		['cartesian closed', ''],
		['coequalizers', ''],
		['equalizers', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['skeletal', 'trivial'],
	],
	'Meas': [
		['cartesian closed', ''],
		['strict terminal object', ''],
		['balanced', ''],
		['skeletal', 'trivial'],
	],
	'N': [
		['countable coproducts', ''],
		['essentially finite', ''],
	],
	'Cat': [
		['strict terminal object', ''],
		['finitary algebraic', ''],
		['balanced', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'On': [
		['terminal object', ''],
		['well-copowered', ''],
	],
	'LRS': [
		['cartesian closed', ''],
		['strict terminal object', ''],
		['skeletal', 'trivial'],
	],
	'Sch': [
		['coequalizers', ''],
		['countable products', ''],
		['cartesian closed', ''],
		['strict terminal object', ''],
		['skeletal', 'trivial'],
	],
	'Fld': [
		['connected', ''],
		['well-copowered', ''],
		['pushouts', ''],
		['balanced', ''],
		['generator', ''],
		['cogenerator', ''],
		['skeletal', 'trivial'],
	],
	'FreeAb': [
		['countable products', ''],
		['balanced', ''],
		['filtered colimits', 'https://math.stackexchange.com/questions/5025660'],
		['skeletal', 'trivial'],
	],
	'Z': [
		['locally essentially small', ''],
		['strict terminal object', ''],
		['skeletal', 'trivial'],
	],
	'BG': [
		['zero morphisms', ''],
		['essentially finite', ''],
	],
	'BGf': [['zero morphisms', '']],
	'BN': [
		['essentially finite', ''],
		['zero morphisms', ''],
		['equalizers', ''],
		['sequential limits', ''],
	],
	'walking_pair': [
		['initial object', ''],
		['zero morphisms', ''],
		['binary products', ''],
		['equalizers', ''],
		['pullbacks', ''],
	],
	'walking_isomorphism': [['skeletal', 'The two objects are isomorphic, but different.']],
	'Setne': [
		['binary coproducts', ''],
		['strict terminal object', ''],
		['sequential limits', ''],
		['skeletal', 'trivial'],
	],
	'B': [
		['small', ''],
		['connected', ''],
		['generator', ''],
		['essentially finite', ''],
		['skeletal', 'trivial'],
	],
	'FI': [
		['binary coproducts', ''],
		['small', ''],
		['cogenerator', ''],
		['binary products', ''],
		['sequential colimits', ''],
		['essentially finite', ''],
		['skeletal', 'trivial'],
	],
	'FS': [
		['small', ''],
		['connected', ''],
		['generator', ''],
		['sequential limits', ''],
		['pullbacks', ''],
		['essentially finite', ''],
		['skeletal', 'trivial'],
	],
	'On+': [
		['locally essentially small', ''],
		['initial object', ''],
		['terminal object', ''],
		['right cancellative', ''],
		['zero morphisms', ''],
		['balanced', ''],
		['binary products', ''],
		['binary coproducts', ''],
		['well-powered', ''],
	],
	'FinOrd': [
		['small', ''],
		['binary coproducts', ''],
		['strict terminal object', ''],
		['subobject classifier', ''],
		['cartesian closed', ''],
		['sequential colimits', ''],
		['countable products', ''],
		['skeletal', 'trivial'],
	],
	'Rel': [
		['preadditive', ''],
		['Cauchy complete', ''],
		['skeletal', 'trivial'],
	],
	'Sp': [
		['locally small', ''],
		['strict terminal object', ''],
		['countable products', ''],
		['countable coproducts', ''],
		['skeletal', 'trivial'],
	],
	'real_interval': [
		['essentially finite', ''],
		['locally finitely presentable', ''],
	],
}
