import type { CategoryID } from './categories.data'

export const CATEGORY_RELATIONS: Record<CategoryID, CategoryID[]> = {
	'0': [],
	'1': ['2'],
	'2': ['1'],
	'Ab': ['Grp', 'R-Mod', 'FinAb'],
	'Abfg': ['Ab', 'FinAb'],
	'B': ['FI', 'FS'],
	'Ban': [],
	'BG': ['BGf', 'BN'],
	'BGf': ['BG', 'BN'],
	'BN': ['BG', 'On+'],
	'Cat': [],
	'CRing': ['Ring', 'Rng'],
	'FI': ['B', 'FS'],
	'FinAb': ['Ab', 'Abfg'],
	'FinOrd': ['Pos', 'FinSet'],
	'FinSet': ['Set'],
	'Fld': ['CRing'],
	'FreeAb': ['Ab'],
	'FS': ['B', 'FI'],
	'Grp': ['Ab', 'Mon'],
	'I': ['walking_isomorphism', 'walking_pair'],
	'LRS': ['Sch'],
	'M-Set': ['R-Mod'],
	'Man': [],
	'Meas': [],
	'Met': ['Met_oo', 'Met_c'],
	'Met_c': ['Met', 'Met_oo', 'Top'],
	'Met_oo': ['Met', 'Met_c'],
	'Mon': ['Grp'],
	'N': ['On', 'real_interval'],
	'On': ['N'],
	'On+': ['BN'],
	'Pos': ['FinOrd'],
	'R-Mod': ['Ab', 'M-Set', 'Vect'],
	'real_interval': ['N'],
	'Rel': ['Set'],
	'Ring': ['CRing', 'Rng'],
	'Rng': ['Ring', 'CRing'],
	'Sch': ['LRS', 'Z'],
	'Set': ['FinSet', 'Set*'],
	'Set*': ['Set'],
	'Setne': ['Set'],
	'Sp': ['B', 'FinSet'],
	'sSet': [],
	'Top': ['Met_c'],
	'Vect': ['R-Mod'],
	'walking_isomorphism': ['I', '1'],
	'walking_pair': ['I'],
	'Z': ['Sch', 'Set'],
}
