import type { CategoryID } from './categories.data'
import type { DescriptionWithReason } from './category-epimorphisms.data'

// format: { category_id: [description of the isomorphisms, reason why this is so] }

export const CATEGORY_ISOMORPHISMS: Record<CategoryID, DescriptionWithReason> = {
	'0': ["there aren't any", ''],
	'1': ['every morphism', ''],
	'2': ['every morphism', ''],
	'Set': ['bijective maps', ''],
	'Ab': ['bijective homomorphisms', ''],
	'Top': ['homeomorphisms', ''],
	'Grp': ['bijective homomorphisms', ''],
	'Vect': ['bijective linear maps', ''],
	'Ring': ['bijective ring homomorphisms', ''],
	'CRing': ['bijective ring homomorphisms', ''],
	'Rng': ['bijective rng homomorphisms', ''],
	'FinSet': ['bijective maps', ''],
	'FinAb': ['bijective homomorphisms', ''],
	'Abfg': ['bijective homomorphisms', ''],
	'Set*': ['bijective pointed maps', ''],
	'sSet': ['natural isomorphisms', ''],
	'Mon': ['bijective homomorphisms', ''],
	'Pos': ['bijective order-preserving and order-reflecting functions', ''],
	'I': ['the two identities', ''],
	'M-Set': ['bijective $M$-maps', ''],
	'R-Mod': ['bijective $R$-linear maps', ''],
	'Met': ['bijective isometries', ''],
	'Met_oo': ['bijective isometries', ''],
	'Met_c': ['homeomorphisms', ''],
	'Ban': ['bijective linear isometries', ''],
	'Man': ['diffeomorphisms', ''],
	'Meas': ['bijective measurable maps that map measurable sets to measurable sets', ''],
	'N': ['only the identity morphisms', ''],
	'Cat': ['functors that are bijective on objects and morphisms', ''],
	'On': ['only the identities', ''],
	'LRS': ['pairs $(f,f^{\\sharp})$ consisting of a homeomorphism $f$ and an isomorphism of sheaves $f^{\\sharp}$', ''],
	'Sch': ['pairs $(f,f^{\\sharp})$ consisting of a homeomorphism $f$ and an isomorphism of sheaves $f^{\\sharp}$', ''],
	'Fld': ['bijective field homomorphisms', ''],
	'FreeAb': ['bijective homomorphisms', ''],
	'Z': ['natural isomorphisms', ''],
	'BG': ['every morphism', ''],
	'BGf': ['every morphism', ''],
	'BN': ['only the number $0$', ''],
	'walking_pair': ['the two identities', ''],
	'walking_isomorphism': ['every morphism', ''],
	'Setne': ['bijective maps', ''],
	'B': ['every morphism', ''],
	'FI': ['bijective maps', ''],
	'FS': ['bijective maps', ''],
	'On+': ['only the ordinal $0$', ''],
	'FinOrd': ['bijective order-preserving maps', ''],
	'Rel': ['bijective functions', ''],
	'Sp': ['natural isomorphisms', ''],
	'real_interval': ['only the identity morphisms', ''],
}
