#!/usr/bin/env sh
set -e

pnpm check

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    pnpm db:create:remote
    pnpm db:check:remote
  fi
done